# -*- coding: utf-8 -*-
"""LMS Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pNu2lXDQC9KudRmIcpuK2R8wIO5JTw5
"""

# Project: library management System
# 4 Modules: add book, issue book, return book, view books

library = []

def add_books():
    book = input("Enter book to be added: ")
    library.append(book)
    print(f"'{book}' has been added to the library")

def issue_books():
    book = input("Enter book to be issued: ")
    if book in library:
        library.remove(book)
        print(f"'{book}' has been issued")
    else:
        print("Book not found")

def return_books():
    book = input("Enter book to be returned: ")
    library.append(book)
    print(f"'{book}' has been returned")

def view_books():
    if not library:
        print("No books in the library")
    else:
        print("List of books:")
        idx = 1
        for book in library:
            print(f"{idx}. {book}")
            idx += 1
    print()

while True:
    print("-----Library Management System-----")
    print("1. Add Books")
    print("2. Issue Books")
    print("3. Return Books")
    print("4. View Books")
    print("5. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        add_books()
    elif choice == 2:
        issue_books()
    elif choice == 3:
        return_books()
    elif choice == 4:
        view_books()
    elif choice == 5:
        print("Exiting Library Management System")
        break
    else:
        print("Invalid choice. Please try again.")